name: Aktualizacja Wyników SRS

on:
  workflow_dispatch:

  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: write

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie plików
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ustawienie Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja bibliotek Python
        run: |
          pip install requests beautifulsoup4 playwright

      - name: Instalacja Chromium
        run: |
          python -m playwright install --with-deps chromium

      - name: Pobieranie wyników
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py

      - name: Sprawdzenie danych
        run: |
          echo "ZAWARTOŚĆ known_events.json:"
          cat known_events.json || true

          echo ""
          echo "STATUS GIT:"
          git status

      - name: Zapisanie zmian
        run: |
          git config --global user.name "SRS Results Bot"
          git config --global user.email "results@srs.local"

          git add -f known_events.json

          git status

          git commit -m "Aktualizacja wyników SRS" || echo "Brak nowych zmian"

          git push
