name: Aktualizacja Rankingu SRS

on:
  workflow_dispatch:

  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  update-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie plików
        uses: actions/checkout@v4

      - name: Ustawienie Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja bibliotek
        run: |
          pip install requests beautifulsoup4

      - name: Aktualizacja rankingu
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py

      - name: Zapisanie zmian
        run: |
          git config --global user.name "SRS Ranking Bot"
          git config --global user.email "ranking@srs.local"
          git add message_ids.txt
          git commit -m "Aktualizacja ID wiadomości rankingu" || exit 0
          git push
