name: Aktualizacja Rankingu SRS

on:
  workflow_dispatch:

  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

jobs:
  update-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie plików
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Ustawienie Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja bibliotek
        run: |
          pip install requests beautifulsoup4

      - name: Aktualizacja rankingu
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py

      - name: Sprawdzenie pliku message_ids
        run: |
          echo "========== PLIK =========="
          ls -la

          echo ""
          echo "========== ZAWARTOŚĆ =========="

          if [ -f message_ids.txt ]; then
            cat message_ids.txt
          else
            echo "BRAK message_ids.txt"
          fi

          echo ""
          echo "========== STATUS GIT =========="
          git status --short

      - name: Zapisanie nowych ID do GitHub
        run: |
          git config user.name "SRS Ranking Bot"
          git config user.email "ranking@srs.local"

          git add message_ids.txt

          echo "========== PO GIT ADD =========="
          git status --short

          if git diff --cached --quiet; then
            echo "Brak zmian do zapisania"
          else
            git commit -m "Aktualizacja ID rankingu SRS"
            git push
          fi
