name: SRS Discord Track Bot

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:

jobs:
  send-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz ostatnie losowanie
        id: track
        run: |
          DATA=$(curl -s "https://srs-losowanie-default-rtdb.firebaseio.com/srsLastTrack.json")

          echo "Dane z Firebase:"
          echo "$DATA"

          TRACK=$(echo "$DATA" | jq -r '.track // empty')
          SEND=$(echo "$DATA" | jq -r '.send // false')

          echo "track=$TRACK" >> $GITHUB_OUTPUT
          echo "send=$SEND" >> $GITHUB_OUTPUT

      - name: Wyślij wynik na Discord
        if: steps.track.outputs.send == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TRACK: ${{ steps.track.outputs.track }}
        run: |
          jq -n \
            --arg track "$TRACK" \
            '{
              content: (
                "🏁 **SRS LOSOWANIE TORU**\n\n" +
                "🎲 Wylosowany tor: 🏆 **" + $track + "**\n\n" +
                "🔥 Powodzenia na torze!"
              )
            }' | curl \
              -H "Content-Type: application/json" \
              -d @- \
              "$DISCORD_WEBHOOK"

      - name: Oznacz jako wysłane
        if: steps.track.outputs.send == 'true'
        run: |
          curl -X PATCH \
            -H "Content-Type: application/json" \
            -d '{"send":false}' \
            "https://srs-losowanie-default-rtdb.firebaseio.com/srsLastTrack.json"
