name: SRS Discord Track Bot

on:
  repository_dispatch:
    types: [send_track]

  workflow_dispatch:

jobs:
  send-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Wyślij wynik na Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TRACK: ${{ github.event.client_payload.track }}
        run: |
          jq -n \
            --arg track "$TRACK" \
            '{
              content: (
                "🏁 **SRS LOSOWANIE TORU**\n\n" +
                "🎲 Wylosowany tor: 🏆 **" + $track + "**\n\n" +
                "🔥 Powodzenia na torze!"
              )
            }' | curl \
              -H "Content-Type: application/json" \
              -d @- \
              "$DISCORD_WEBHOOK"
